name: unit-tests

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  test-plugin:
    if: contains(github.event.head_commit.message, 'skip ci') == false
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup wasm32-wasi
      run: rustup target add wasm32-wasi

    - name: Lint
      run: cargo fmt --all --check

    - name: Run tests
      run: cargo test --workspace --verbose -- --include-ignored

  test-runtime:
    if: contains(github.event.head_commit.message, 'skip ci') == false
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'

      - name: Caching dependencies
        id: node-modules-caches
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
          restore-keys: |
            ${{ runner.os }}-yarn-
    
      - if: steps.node-modules-caches.outputs.cache-hit != 'true'
        run: yarn --frozen-lockfile

      - run: yarn test:runtime
